name: Deploy to Azure Web App

on:
  push:
    branches:
      - main   # your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Optional: you can build if needed
      - name: Set up Node.js (if you have scripts using npm)
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or whatever version you need

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'health-connect-ui'           # replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './static_pages'                           # path to your HTML/CSS/JS files
