name: Build and deploy frontend to Azure Web App - health-connect-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A56B88854EA94C4CB7E1BE99AD149CB2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4A32BD7C9A5242AD846D75782BECDA7D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3F9E5C53E53541D9B7C61D9FB3DAED33 }}

      # Deploy directly to Azure Web App using publish profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'health-connect-ui' # 👈 your Azure Web App name
          package: './static_ui_pages'


