name: Build and deploy frontend to Azure Web App - health-connect-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy directly to Azure Web App using publish profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'health-connect-ui' # 👈 your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './static_ui_pages'
